language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential gfortran perl g++ gcc cmake m4 git
  - sudo apt-get install -y liblapack-dev liblapack-doc liblapack3gf
  - sudo apt-get install -y libblas-dev libblas-doc libblas3gf
  - echo `pwd`
install:
  - ls ./deps
  - ls -lh ./deps/travis-install-mpi.sh
  - sudo ./deps/travis-install-mpi.sh mpich3
#  - julia -e 'Pkg.clone("MPI")'
#  - julia -e 'Pkg.build("MPI")'
  - ls ./
  - ls ../
  - ls -a ~
#  - ls -a ~/.julia
#  - ls ~/.julia/v0.4
 
  
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("PETSc")'
  - echo $HOME
  - echo `pwd`
  - ls -a ~
  - ls -a ~/.julia
  - cd ~/.julia/v0.4/PETSc
#  - ./test/runtests.sh
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("PETSc"); Pkg.test("PETSc"; coverage=true)'
   - julia --check-bounds=yes -e 'Pkg.test("PETSc"; converage=true)'
#  - julia --check-bounds=yes ./test/test_singlereal.jl
